In [2]:
import pandas as pd

In [29]:
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0

In [3]:
df = pd.read_csv('orders_data.csv')
df.head(7)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,10-01-2023,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,18-06-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,13-07-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,13-03-2022,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,28-12-2022,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3

In [4]:
df.shape

(9994, 16)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   str
 2   Ship Mode         9993 non-null   str
 3   Segment           9994 non-null   str
 4   Country           9994 non-null   str
 5   City              9994 non-null   str
 6   State             9994 non-null   str
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   str
 9   Category          9994 non-null   str
 10  Sub Category      9994 non-null   str
 11  Product Id        9994 non-null   str
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), str(10)
memory usage: 2.2 MB

In [6]:
df['Ship Mode'].unique()

<ArrowStringArray>
[  'Second Class', 'Standard Class',  'Not Available',        'unknown',
    'First Class',              nan,       'Same Day']
Length: 7, dtype: str

In [7]:
# I want to consider Not-Availabe, unkown as NA only
df1 = pd.read_csv('orders_data.csv', na_values=['Not Available', 'unknown'])
df1['Ship Mode'].unique()

<ArrowStringArray>
['Second Class', 'Standard Class', nan, 'First Class', 'Same Day']
Length: 5, dtype: str

In [8]:
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,10-01-2023,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,18-06-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,13-07-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [9]:
# calculating selling price
df1['Selling_Price'] = df1['List Price'] - df1['List Price']*(df1['Discount Percent'] / 100)
df1['Selling_Price']

0       254.8
1       708.1
2         9.5
3       940.8
4        19.0
        ...
9989     28.8
9990     86.4
9991    254.8
9992     29.1
9993    232.8
Name: Selling_Price, Length: 9994, dtype: float64

In [10]:
df1.head(5)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Selling_Price
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,254.8
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,708.1
2,3,10-01-2023,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,9.5
3,4,18-06-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,940.8
4,5,13-07-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,19.0

In [11]:
df1['Profit'] = df1['Selling_Price'] - df1['cost price']
df1['Profit']

0        14.8
1       108.1
2        -0.5
3       160.8
4        -1.0
        ...
9989     -1.2
9990     16.4
9991     34.8
9992     -0.9
9993     22.8
Name: Profit, Length: 9994, dtype: float64

In [12]:
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,Selling_Price,Profit
0,1,01-03-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,254.8,14.8
1,2,15-08-2023,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,708.1,108.1
2,3,10-01-2023,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,9.5,-0.5
3,4,18-06-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,940.8,160.8
4,5,13-07-2022,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,19.0,-1.0

In [13]:
df1.rename(columns={'Profit':'Unit_Profit', 'Selling_Price':'Unit_Selling_Price'}, inplace=True)

In [14]:
df1.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent', 'Unit_Selling_Price', 'Unit_Profit'],
      dtype='str')

In [15]:
df1.dtypes

Order Id                int64
Order Date                str
Ship Mode                 str
Segment                   str
Country                   str
City                      str
State                     str
Postal Code             int64
Region                    str
Category                  str
Sub Category              str
Product Id                str
cost price              int64
List Price              int64
Quantity                int64
Discount Percent        int64
Unit_Selling_Price    float64
Unit_Profit           float64
dtype: object

In [16]:
#changing datatype of order date column from str to datetime

In [17]:
df1['Order Date'] = pd.to_datetime(df1['Order Date'], format='%d-%m-%Y')

In [18]:
df1.dtypes

Order Id                       int64
Order Date            datetime64[us]
Ship Mode                        str
Segment                          str
Country                          str
City                             str
State                            str
Postal Code                    int64
Region                           str
Category                         str
Sub Category                     str
Product Id                       str
cost price                     int64
List Price                     int64
Quantity                       int64
Discount Percent               int64
Unit_Selling_Price           float64
Unit_Profit                  float64
dtype: object

In [19]:
df1.drop(columns= ['cost price', 'List Price', 'Discount Percent'], inplace=True)

In [20]:
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0

In [21]:
#calculating total Profit in each order

In [22]:
df1['Total Profit'] = df1['Quantity'] * df1['Unit_Profit']
df1['Total Profit']

0        29.6
1       324.3
2        -1.0
3       804.0
4        -2.0
        ...
9989     -3.6
9990     32.8
9991     69.6
9992     -3.6
9993     45.6
Name: Total Profit, Length: 9994, dtype: float64

In [23]:
# Exporting DataFrame to sql using sqlaclchemy libraby

In [24]:
%pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
import sqlalchemy as sal

In [73]:
# creating an engine to connect with SQL
# instead of mssql if we are connecting with mysql or postgresql, write them.
# server name
# project - database name

engine = sal.create_engine('mssql://LAPTOP-0AA9NCKM\SQLEXPRESS/python_project?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes')

In [74]:
conn=engine.connect()
conn

In [75]:
df1.to_sql('orders_data', con=conn, index=False, if_exists = 'replace') # or if_exists = 'append'

94

In [29]:
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0

In [30]:
# Q1. Find top 10 highest profit generating products

In [31]:
df1.groupby('Product Id')

In [32]:
df1.groupby('Product Id')['Total Profit'].sum()

Product Id
FUR-BO-10000112     405.9
FUR-BO-10000330     560.0
FUR-BO-10000362     638.6
FUR-BO-10000468     380.6
FUR-BO-10000711     345.9
                    ...
TEC-PH-10004912     203.8
TEC-PH-10004922     259.2
TEC-PH-10004924      -6.0
TEC-PH-10004959      74.4
TEC-PH-10004977    1593.2
Name: Total Profit, Length: 1862, dtype: float64

In [33]:
df1.groupby('Product Id', as_index=False)['Total Profit'].sum().sort_values(
    by='Total Profit', ascending=False
).reset_index()[['Product Id', 'Total Profit']].head(10)

        Product Id  Total Profit
0  TEC-CO-10004722       24816.0
1  TEC-MA-10002412       21746.4
2  OFF-BI-10000545       17867.7
3  TEC-CO-10001449       15948.0
4  FUR-CH-10002024       13930.7
5  OFF-BI-10003527       12792.9
6  TEC-PH-10001459       11481.9
7  TEC-MA-10000822       10102.3
8  FUR-TA-10000198       10015.1
9  TEC-MA-10001047        9989.0

In [34]:
# create a column for total sales value of each order

In [35]:
df1['Total_Sale'] = df1['Unit_Selling_Price'] * df1['Quantity']
df1.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total_Sale
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0,19.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0,4704.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0,38.0

In [36]:
# write a python code to list all distinct cities where orders have been shipped

In [37]:
df1['City'].unique()

<ArrowStringArray>
[        'Henderson',       'Los Angeles',   'Fort Lauderdale',
           'Concord',           'Seattle',        'Fort Worth',
           'Madison',       'West Jordan',     'San Francisco',
           'Fremont',
 ...
        'Hagerstown',       'East Orange', 'Arlington Heights',
            'Oswego',       'Coon Rapids',      'San Clemente',
   'San Luis Obispo',        'Springdale',              'Lodi',
             'Mason']
Length: 531, dtype: str

In [38]:
# Find all orders from the Technology category that were shipped using Second class ship mode orderd by order date

In [39]:
df1[(df1['Category']== 'Technology') & (df1['Ship Mode'] == 'Second class')]
df1.head(15)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total_Sale
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0,19.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0,4704.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0,38.0
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,7,48.5,-1.5,-10.5,339.5
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,4,9.7,-0.3,-1.2,38.8
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,6,864.5,4.5,27.0,5187.0
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,3,19.6,-0.4,-1.2,58.8
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,5,106.7,16.7,83.5,533.5
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,9,1658.7,188.7,1698.3,14928.3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,4,882.7,132.7,530.8,3530.8
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,3,19.4,-0.6,-1.8,58.2
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,3,401.8,41.8,125.4,1205.4
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,5,66.5,6.5,32.5,332.5

In [40]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\ProgramData\anaconda3\Lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

In [41]:
# Find the average order value

In [42]:
import numpy as np
np.mean(df1['Total_Sale'])

np.float64(1108.5979787872723)

In [43]:
#Find the city with the highest total quantity of products ordered.

In [44]:
df1.groupby('City')['Quantity'].sum().reset_index().sort_values(by = ['Quantity'], ascending = False)

              City  Quantity
329  New York City      3417
266    Los Angeles      2879
374   Philadelphia      1981
438  San Francisco      1935
452        Seattle      1590
..             ...       ...
257    Lindenhurst         1
221        Jupiter         1
213      Iowa City         1
386    Port Orange         1
140         Elyria         1

[531 rows x 2 columns]

In [45]:
#Rank orders in each region by quantity in descending orders

In [47]:
df1[['Order Id', 'Region', 'Quantity']].sort_values(by=['Region', 'Quantity'], ascending = [True, False])

      Order Id   Region  Quantity
660        661  Central        14
1045      1046  Central        14
7387      7388  Central        14
8074      8075  Central        14
9515      9516  Central        14
...        ...      ...       ...
9752      9753     West         1
9838      9839     West         1
9902      9903     West         1
9953      9954     West         1
9986      9987     West         1

[9994 rows x 3 columns]

In [ ]:
#list all orders placed in the first quarter of any year(January to March), including the total cost for these orders.

In [48]:
df1.head(3)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total_Sale
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0,19.0

In [51]:
df1['Month']= df1['Order Date'].dt.month
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total_Sale,Month
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8

In [52]:
df1[df1['Month'].isin([1,2,3])]

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total_Sale,Month
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0,19.0,1
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,7,48.5,-1.5,-10.5,339.5,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,6,864.5,4.5,27.0,5187.0,1
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,3,19.6,-0.4,-1.2,58.8,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9963,9964,2022-01-17,Same Day,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Paper,OFF-PA-10003072,2,9.7,-0.3,-0.6,19.4,1
9966,9967,2022-02-21,Second Class,Corporate,United States,Newark,Delaware,19711,East,Office Supplies,Envelopes,OFF-EN-10004483,7,105.6,5.6,39.2,739.2,2
9973,9974,2023-03-07,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10004080,5,259.2,29.2,146.0,1296.0,3
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,28.8,-1.2,-3.6,86.4,2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,86.4,16.4,32.8,172.8,3

In [ ]:
# Find the top 3 highest selling products in each region acc to quantity

In [54]:
df1.groupby(['Region', 'Product Id'])['Quantity'].sum().reset_index().sort_values(by = ['Region', 'Quantity'], ascending =[True, False])

       Region       Product Id  Quantity
461   Central  OFF-BI-10000301        34
474   Central  OFF-BI-10000756        33
470   Central  OFF-BI-10000546        29
491   Central  OFF-BI-10001249        29
61    Central  FUR-CH-10002304        27
...       ...              ...       ...
5219     West  TEC-PH-10002185         1
5227     West  TEC-PH-10002447         1
5229     West  TEC-PH-10002483         1
5256     West  TEC-PH-10003357         1
5276     West  TEC-PH-10004120         1

[5298 rows x 3 columns]

In [ ]:
# Total sale in each Region

In [57]:
df1.groupby('Region')['Total_Sale'].sum().reset_index().sort_values(by =['Total_Sale'], ascending=True)

    Region  Total_Sale
2    South   1966053.6
0  Central   2387881.2
1     East   3257983.8
3     West   3467409.6

In [ ]:
# Find top 5 highest selling products in each region according to sales

In [58]:
df1['Year'] = df1['Order Date'].dt.year
df1.head(2)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit,Total_Sale,Month,Year
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6,509.6,3,2023
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3,2124.3,8,2023

In [ ]:
#Find month over month growth compariosn for 2022 and 2023

In [61]:
a = df1.groupby(['Month','Year'])['Total_Sale'].sum().reset_index()

In [63]:
pivot_table = a.pivot_table(index='Month', columns='Year', values='Total_Sale', aggfunc='sum')
pivot_table

Year       2022      2023
Month
1      437431.3  434765.5
2      444011.1  731638.8
3      394105.2  393051.9
4      476400.9  543231.5
5      413625.5  410707.9
6      465300.3  328939.0
7      375278.4  422533.7
8      534562.4  465010.3
9      433887.0  420620.5
10     601707.8  626498.3
11     451809.6  334940.6
12     447421.8  491848.9

In [64]:
pivot_table = pivot_table.reset_index()
pivot_table

Year  Month      2022      2023
0         1  437431.3  434765.5
1         2  444011.1  731638.8
2         3  394105.2  393051.9
3         4  476400.9  543231.5
4         5  413625.5  410707.9
5         6  465300.3  328939.0
6         7  375278.4  422533.7
7         8  534562.4  465010.3
8         9  433887.0  420620.5
9        10  601707.8  626498.3
10       11  451809.6  334940.6
11       12  447421.8  491848.9

In [66]:
pivot_table['YoY_growth'] = pivot_table[2023]-pivot_table[2022]
pivot_table

Year  Month      2022      2023  YoY_growth
0         1  437431.3  434765.5     -2665.8
1         2  444011.1  731638.8    287627.7
2         3  394105.2  393051.9     -1053.3
3         4  476400.9  543231.5     66830.6
4         5  413625.5  410707.9     -2917.6
5         6  465300.3  328939.0   -136361.3
6         7  375278.4  422533.7     47255.3
7         8  534562.4  465010.3    -69552.1
8         9  433887.0  420620.5    -13266.5
9        10  601707.8  626498.3     24790.5
10       11  451809.6  334940.6   -116869.0
11       12  447421.8  491848.9     44427.1

In [ ]:
#Reading data from sql server in Python

In [67]:
%pip  install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in C:\ProgramData\anaconda3\Lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [68]:
import pyodbc

In [70]:
#properly formatted connection string
conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    r'SERVER=LAPTOP-0AA9NCKM\SQLEXPRESS;'
    'DATABASE=python_project;'
    'Trusted_Connection=yes;'
)

In [71]:
df = pd.read_sql_query('select * from orders_data', conn)
df.head()

C:\Users\Roshan Jha\AppData\Local\Temp\ipykernel_8184\3297801732.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from orders_data', conn)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,Quantity,Unit_Selling_Price,Unit_Profit,Total Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,254.8,14.8,29.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,708.1,108.1,324.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,9.5,-0.5,-1.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,940.8,160.8,804.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,19.0,-1.0,-2.0